from pathlib import Path
import subprocess,re,json,html
from urllib.parse import unquote
p=Path('index.html'); text=p.read_text(encoding='utf-8')
start='/* Final exact Insights specificity START */'; end='/* Final exact Insights specificity END */'
sections=['company','points','founder','experience','network','capabilities']
prefix=','.join(f'#{s}#{s} .exact-insights-heading' for s in sections)
# Deliberately use doubled IDs so this wins over every legacy !important selector.
css='''/* Final exact Insights specificity START */
#company#company .exact-insights-heading,#points#points .exact-insights-heading,#founder#founder .exact-insights-heading,#experience#experience .exact-insights-heading,#network#network .exact-insights-heading,#capabilities#capabilities .exact-insights-heading{display:block!important;width:100%!important;max-width:760px!important;margin:0 0 24px 0!important;padding:0!important;text-align:left!important;box-sizing:border-box!important}
#company#company .exact-insights-heading .heading-ref-row,#points#points .exact-insights-heading .heading-ref-row,#founder#founder .exact-insights-heading .heading-ref-row,#experience#experience .exact-insights-heading .heading-ref-row,#network#network .exact-insights-heading .heading-ref-row,#capabilities#capabilities .exact-insights-heading .heading-ref-row{display:flex!important;align-items:center!important;justify-content:flex-start!important;gap:12px!important;width:fit-content!important;max-width:100%!important;margin:0 0 18px 0!important;padding:0!important;font-family:Arial,Helvetica,sans-serif!important;font-size:11px!important;font-weight:900!important;line-height:16.5px!important;letter-spacing:1.87px!important;color:rgb(200,181,110)!important;text-align:left!important;text-transform:none!important;white-space:normal!important;background:none!important;border:0!important;border-radius:0!important;box-shadow:none!important}
#company#company .exact-insights-heading h2,#points#points .exact-insights-heading h2,#founder#founder .exact-insights-heading h2,#experience#experience .exact-insights-heading h2,#network#network .exact-insights-heading h2,#capabilities#capabilities .exact-insights-heading h2{display:block!important;width:fit-content!important;max-width:100%!important;margin:0 0 14px 0!important;padding:0!important;font-family:Arial,Helvetica,sans-serif!important;font-size:clamp(34px,4vw,58px)!important;font-weight:700!important;line-height:normal!important;letter-spacing:-.04em!important;color:rgb(247,245,239)!important;text-align:left!important;text-transform:none!important;white-space:normal!important;background:none!important;border:0!important;box-shadow:none!important;text-shadow:none!important;-webkit-text-stroke:0!important}
#company#company .exact-insights-heading::before,#company#company .exact-insights-heading::after,#points#points .exact-insights-heading::before,#points#points .exact-insights-heading::after,#founder#founder .exact-insights-heading::before,#founder#founder .exact-insights-heading::after,#experience#experience .exact-insights-heading::before,#experience#experience .exact-insights-heading::after,#network#network .exact-insights-heading::before,#network#network .exact-insights-heading::after,#capabilities#capabilities .exact-insights-heading::before,#capabilities#capabilities .exact-insights-heading::after,#company#company .heading-ref-row::before,#company#company .heading-ref-row::after,#points#points .heading-ref-row::before,#points#points .heading-ref-row::after,#founder#founder .heading-ref-row::before,#founder#founder .heading-ref-row::after,#experience#experience .heading-ref-row::before,#experience#experience .heading-ref-row::after,#network#network .heading-ref-row::before,#network#network .heading-ref-row::after,#capabilities#capabilities .heading-ref-row::before,#capabilities#capabilities .heading-ref-row::after{content:none!important;display:none!important;width:0!important;height:0!important;min-width:0!important;min-height:0!important;margin:0!important;padding:0!important;border:0!important;background:none!important;background-image:none!important;box-shadow:none!important}
#company#company .exact-insights-heading .section-kicker-icon,#company#company .exact-insights-heading .section-sport-icon,#points#points .exact-insights-heading .section-kicker-icon,#points#points .exact-insights-heading .section-sport-icon,#founder#founder .exact-insights-heading .section-kicker-icon,#founder#founder .exact-insights-heading .section-sport-icon,#experience#experience .exact-insights-heading .section-kicker-icon,#experience#experience .exact-insights-heading .section-sport-icon,#network#network .exact-insights-heading .section-kicker-icon,#network#network .exact-insights-heading .section-sport-icon,#capabilities#capabilities .exact-insights-heading .section-kicker-icon,#capabilities#capabilities .exact-insights-heading .section-sport-icon{display:none!important;visibility:hidden!important;width:0!important;height:0!important;margin:0!important;padding:0!important}
#network#network .exact-insights-heading .hierarchy-support,#network#network .exact-insights-heading .major-support,#capabilities#capabilities .exact-insights-heading .hierarchy-support{display:block!important;width:100%!important;max-width:760px!important;margin:0!important;padding:0!important;font-family:Arial,Helvetica,sans-serif!important;font-size:15px!important;font-weight:500!important;line-height:1.5!important;letter-spacing:0!important;color:#9da7b4!important;text-align:left!important}
@media(max-width:760px){#founder#founder .exact-insights-heading .founder-name-support{display:none!important}#network#network .exact-insights-heading .hierarchy-support,#network#network .exact-insights-heading .major-support,#capabilities#capabilities .exact-insights-heading .hierarchy-support{font-size:14px!important}}
/* Final exact Insights specificity END */'''
pat=re.escape(start)+r'.*?'+re.escape(end)
if re.search(pat,text,re.S): text=re.sub(pat,css,text,count=1,flags=re.S)
else: text=text.replace('</head>','<style>'+css+'</style>\n</head>',1)
p.write_text(text,encoding='utf-8')

probe=r'''<script>setTimeout(function(){function s(e){return getComputedStyle(e)}function vis(sec){return [].slice.call(document.querySelectorAll(sec+' .exact-insights-heading')).find(function(e){var q=s(e),r=e.getBoundingClientRect();return q.display!=='none'&&q.visibility!=='hidden'&&r.width>0&&r.height>0})}var rk=document.querySelector('#insights .eyebrow'),rh=document.querySelector('#insights .insight-intro h2'),rl=document.querySelector('#insights .eyebrow span'),rks=s(rk),rhs=s(rh),rls=s(rl),out={};['company','points','founder','experience','network','capabilities'].forEach(function(id){var w=vis('#'+id),k=w&&w.querySelector('.heading-ref-row'),h=w&&w.querySelector('h2'),l=k&&k.querySelector(':scope>span');if(!w||!k||!h||!l){out[id]={ok:false,reason:'missing'};return}var ks=s(k),hs=s(h),ls=s(l);var K=['fontSize','fontWeight','lineHeight','letterSpacing','color','marginBottom','fontFamily'].every(function(x){return ks[x]===rks[x]}),H=['fontSize','fontWeight','lineHeight','letterSpacing','color','marginBottom','fontFamily'].every(function(x){return hs[x]===rhs[x]}),L=['width','height','background'].every(function(x){return ls[x]===rls[x]});var P=[s(w,'::before'),s(w,'::after'),s(k,'::before'),s(k,'::after')].every(function(x){return x.content==='none'||x.display==='none'});var kr=k.getBoundingClientRect(),hr=h.getBoundingClientRect();var A=ks.textAlign==='left'&&hs.textAlign==='left'&&Math.abs(kr.left-hr.left)<1;out[id]={ok:K&&H&&L&&P&&A,K:K,H:H,L:L,noSquare:P,left:A,kicker:{mb:ks.marginBottom,fs:ks.fontSize},heading:{fs:hs.fontSize,fw:hs.fontWeight,ls:hs.letterSpacing,mb:hs.marginBottom},line:{w:ls.width,h:ls.height}}});document.body.setAttribute('data-final-audit',encodeURIComponent(JSON.stringify(out)))},1800)</script>'''
v=text.replace('</body>',probe+'\n</body>',1); vp=Path('.final-audit.html');vp.write_text(v,encoding='utf-8')
chrome='/usr/bin/google-chrome'
if not Path(chrome).exists(): chrome='/usr/bin/chromium'
for width in (1280,390):
 r=subprocess.run([chrome,'--headless=new','--no-sandbox','--disable-gpu','--allow-file-access-from-files','--virtual-time-budget=6500',f'--window-size={width},1200','--dump-dom',vp.resolve().as_uri()],capture_output=True,text=True)
 m=re.search(r'data-final-audit="([^"]+)"',r.stdout)
 if not m: raise SystemExit('audit missing '+str(width))
 d=json.loads(unquote(html.unescape(m.group(1)))); print('FINAL',width,json.dumps(d,ensure_ascii=False)); bad=[k for k,x in d.items() if not x.get('ok')]
 if bad: raise SystemExit('final mismatches '+str(width)+': '+','.join(bad))
vp.unlink(missing_ok=True); print('FINAL SIX EXACT MATCH PASSED')
